version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3131:3131"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Uncomment if you have environment variables
    # env_file:
    #   - .env.production

  # Development service (optional)
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3131:3131"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
    command: yarn dev
    profiles:
      - dev
